# Generated by Django 3.0.8 on 2020-07-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64, verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=64, verbose_name='currency')),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Категорий',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описания')),
                ('number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('date_publeshed', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellomaster.Country')),
                ('currency', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellomaster.Currency')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sellomaster.Rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
