# Generated by Django 3.0.8 on 2020-07-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
